.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. helveticum_qt test_helveticum_qt
clean: FORCE
	$(MAKE) -C .. helveticum_qt_clean test_helveticum_qt_clean
check: FORCE
	$(MAKE) -C .. test_helveticum_qt_check
helveticum-qt helveticum-qt.exe: FORCE
	 $(MAKE) -C .. helveticum_qt
